# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 4 workers
nodes:
  # the control plane node config
  - role: control-plane
    kubeadmConfigPatches:
    - |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      containerLogMaxSize: "50Mi"
  # the four workers
  - role: worker
  - role: worker
  - role: worker
  - role: worker